name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Set Git User
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - name: Update
        run: |
          # Bump Version
          npm version patch --no-git-tag-version

          # Push
          git push --follow-tags
