name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: git-actions/set-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - name: Update
        run: |
          # Bump Version
          npm version patch --no-git-tag-version

          # Push
          git push --follow-tags
