name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh release list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
