name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: gh release create "${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
